Repository Zenika/OZKOUR, pull requests merged in 2022-07, with the labels that each got.

#80 75 slides sur plusieurs pages
  ozkour-back/Utils/dateUtils.js
  ozkour-back/config/.DS_Store
  ozkour-back/config/routes/talk.js
  ozkour-back/google-api/connect.js
  ozkour-back/google-api/sheets.js
  ozkour-back/google-api/slide.js
  ozkour-back/google-api/slideDataOrganizer.js
  ozkour-back/google-api/slideService.js
  ozkour-back/google-api/slideWrapper.js
  ozkour-back/jest.config.js
  ozkour-back/jest.setup.js
  ozkour-back/package-lock.json
  ozkour-back/package.json
  ozkour-back/tests/__snapshots__/slide.test.js.snap
  ozkour-back/tests/__snapshots__/slideDataOrganizer.test.js.snap
  ozkour-back/tests/dataset/slideDataOrganizer/talk.json
  ozkour-back/tests/dataset/slideDataOrganizer/talkClusterDate.json
  ozkour-back/tests/dataset/slideDataOrganizer/talkClusterEvent.json
  ozkour-back/tests/dataset/slideDataOrganizer/talkDisplayNormal.json
  ozkour-back/tests/dataset/slideDataOrganizer/talkNoCluster.json
  ozkour-back/tests/dataset/slideDataOrganizer/talkOverFlow1.json
  ozkour-back/tests/dataset/slideDataOrganizer/talkOverFlow2.json
  ozkour-back/tests/dataset/slideDataOrganizer/talkOverFlow3.json
  ozkour-back/tests/dateUtils.test.js
  ozkour-back/tests/sheets.test.js
  ozkour-back/tests/slide.test.js
  ozkour-back/tests/slideDataOrganizer.test.js
  ozkour-back/tests/utilitary.test.js
Labels: backend, Google Slide

#87 86 - makes the server runnable again
  ozkour-back/config/routes/talk.js
  ozkour-back/index.js
  ozkour-back/tests/index.test.js
Labels: bug, backend

#76 68 créer des variables denvironnement
  .gitignore
  ozkour-back/.gitignore
  ozkour-back/config/routes/test-route.js
  ozkour-back/index.js
  ozkour-back/server.js
  ozkour-back/tests/index.test.js
  ozkour-back/tests/server.test.js
  ozkour-front/.gitignore
  ozkour-front/package.json
  ozkour-front/src/api/apiConfig.js
  ozkour-front/tests/unit/TestDatePicker.spec.js
Labels: frontend, backend, Google Slide

#90 85 - créer un loader lors de la génération de slides
  ozkour-front/src/components/Buttons/PrimaryBtn.vue
  ozkour-front/src/components/RecapModal.vue
  ozkour-front/tests/unit/TestPopUp.spec.js
  ozkour-front/tests/unit/TestPrimaryBtn.spec.js
Labels: frontend

#95 93 add SCSS variables to optimize style in components
  ozkour-front/.eslintrc.json
  ozkour-front/jsconfig.json
  ozkour-front/src/App.vue
  ozkour-front/src/assets/images/logoZenika.png
  ozkour-front/src/assets/logo.png
  ozkour-front/src/assets/variables.scss
  ozkour-front/src/components/Buttons/PrimaryBtn.vue
  ozkour-front/src/components/ChoosingDate.vue
  ozkour-front/src/components/ChoosingTemplate.vue
  ozkour-front/src/components/EventArray.vue
  ozkour-front/src/components/Header-Default.vue
  ozkour-front/src/components/RecapModal.vue
  ozkour-front/src/views/HomeView.vue
  ozkour-front/src/views/TalkForm.vue
  ozkour-front/vue.config.js
Labels: frontend
