Repository Zenika/OZKOUR, pull requests merged in 2022-05, with the labels that each got.

#43 New section in the READ ME
  ozkour-front/README.md
Labels: documentation

#51 46 creation de slide dans le backend
  .DS_Store
  ozkour-back/config/.DS_Store
  ozkour-back/config/routes/error.js
  ozkour-back/config/routes/talk.js
  ozkour-back/google-api/connect.js
  ozkour-back/google-api/slide.js
  ozkour-back/index.js
Labels: backend

#58 52 tests a revoir et a faire
  ozkour-back/config/auth/.DS_Store
  ozkour-back/google-api/sheets.js
  ozkour-back/google-api/slide.js
  ozkour-back/package-lock.json
  ozkour-back/package.json
  ozkour-back/tests/sheets.test.js
  ozkour-back/tests/slide.test.js
  ozkour-back/tests/utilitary.test.js
  ozkour-front/src/components/ChoosingDate.vue
  ozkour-front/src/components/EventArray.vue
  ozkour-front/tests/unit/TestEventArray.spec.js
  ozkour-front/tests/unit/TestStore.spec.js
Labels: frontend, backend
