Repository Zenika/OZKOUR, pull requests merged in 2022-10, with the labels that each got.

#133 130 - templates that cannot be selected by the user are now disabled
  ozkour-front/src/components/ChoosingTemplate.vue
Labels: frontend

#132 131 refacto back-end
  ozkour-back/.eslintignore
  ozkour-back/.gitignore
  ozkour-back/config/.DS_Store
  ozkour-back/config/auth/.DS_Store
  ozkour-back/package-lock.json
  ozkour-back/package.json
  ozkour-back/src/Utils/dateUtils.js
  ozkour-back/src/config/auth/service_account.js
  ozkour-back/src/domain/docsService.js
  ozkour-back/src/domain/emailingOrganizer.js
  ozkour-back/src/domain/model/talk.js
  ozkour-back/src/domain/quoiDe9Organizer.js
  ozkour-back/src/domain/slideService.js
  ozkour-back/src/domain/talks-sheet.js
  ozkour-back/src/domain/type/doc.ts
  ozkour-back/src/domain/type/drive.ts
  ozkour-back/src/domain/type/slide.ts
  ozkour-back/src/index.js
  ozkour-back/src/infrastructure/connect.js
  ozkour-back/src/infrastructure/googledocs/docsWrapper.js
  ozkour-back/src/infrastructure/googledocs/googleDocRepository.js
  ozkour-back/src/infrastructure/googledrive/driveWrapper.js
  ozkour-back/src/infrastructure/googledrive/googleDriveRepository.js
  ozkour-back/src/infrastructure/googlesheets/sheetWrapper.js
  ozkour-back/src/infrastructure/googleslide/googleSlideRepository.js
  ozkour-back/src/infrastructure/googleslide/slideWrapper.js
  ozkour-back/src/routes/error.js
  ozkour-back/src/routes/index.js
  ozkour-back/src/routes/talk.js
  ozkour-back/src/routes/test-route.js
  ozkour-back/src/server.js
  ozkour-back/tests/dateUtils.test.js
  ozkour-back/tests/docs.test.js
  ozkour-back/tests/drive.test.js
  ozkour-back/tests/server.test.js
  ozkour-back/tests/sheets.test.js
  ozkour-back/tests/slide.test.js
  ozkour-back/tests/slideDataOrganizer.test.js
Labels: backend, refactoring

#136 122-ajouter un loader pour la récupération des talks
  ozkour-front/src/components/EventArray.vue
  ozkour-front/src/stores/talks.js
Labels: enhancement, frontend
