Repository Zenika/OZKOUR, pull requests merged in 2022-08, with the labels that each got.

#98 94 récupérer les données de plusieurs années
  ozkour-back/Utils/dateUtils.js
  ozkour-back/domain/talks-sheet.js
  ozkour-back/google-api/drive.js
  ozkour-back/infrastructure/connect.js
  ozkour-back/infrastructure/googledrive/driveWrapper.js
  ozkour-back/infrastructure/googlesheets/sheetWrapper.js
  ozkour-back/server.js
  ozkour-back/tests/__snapshots__/slide.test.js.snap
  ozkour-back/tests/dateUtils.test.js
  ozkour-back/tests/drive.test.js
  ozkour-back/tests/slide.test.js
Labels: enhancement, backend, Google Sheets

#99 96 ajouter authentification
  ozkour-front/package-lock.json
  ozkour-front/package.json
  ozkour-front/src/App.vue
  ozkour-front/src/api/apiConfig.js
  ozkour-front/src/assets/images/arrow-down-1.png
  ozkour-front/src/assets/images/arrow-up-2.png
  ozkour-front/src/assets/images/arrow.svg
  ozkour-front/src/assets/images/login.png
  ozkour-front/src/assets/variables.scss
  ozkour-front/src/components/AuthenticationDefault.vue
  ozkour-front/src/components/Buttons/PrimaryBtn.vue
  ozkour-front/src/components/Header-Default.vue
  ozkour-front/src/components/Links/PrimaryLink.vue
  ozkour-front/src/components/icons/IconArrow.vue
  ozkour-front/src/main.js
  ozkour-front/src/router/index.js
  ozkour-front/src/views/HomeView.vue
  ozkour-front/tests/unit/TestAuthentication.spec.js
  ozkour-front/tests/unit/TestDatePicker.spec.js
  ozkour-front/tests/unit/TestEventArray.spec.js
  ozkour-front/tests/unit/TestPopUp.spec.js
  ozkour-front/tests/unit/TestStore.spec.js
Labels: frontend

#106 Merging dev into main
  ozkour-front/package-lock.json
  ozkour-front/package.json
  ozkour-front/src/App.vue
  ozkour-front/src/api/apiConfig.js
  ozkour-front/src/assets/images/arrow-down-1.png
  ozkour-front/src/assets/images/arrow-up-2.png
  ozkour-front/src/assets/images/arrow.svg
  ozkour-front/src/assets/images/login.png
  ozkour-front/src/assets/variables.scss
  ozkour-front/src/components/AuthenticationDefault.vue
  ozkour-front/src/components/Buttons/PrimaryBtn.vue
  ozkour-front/src/components/Header-Default.vue
  ozkour-front/src/components/Links/PrimaryLink.vue
  ozkour-front/src/components/icons/IconArrow.vue
  ozkour-front/src/main.js
  ozkour-front/src/router/index.js
  ozkour-front/src/views/HomeView.vue
  ozkour-front/tests/unit/TestAuthentication.spec.js
  ozkour-front/tests/unit/TestDatePicker.spec.js
  ozkour-front/tests/unit/TestEventArray.spec.js
  ozkour-front/tests/unit/TestPopUp.spec.js
  ozkour-front/tests/unit/TestStore.spec.js
Labels: production

#108 84 architecture hexagonale
  ozkour-back/Utils/dateUtils.js
  ozkour-back/config/routes/talk.js
  ozkour-back/domain/model/talk.js
  ozkour-back/domain/slideDataOrganizer.js
  ozkour-back/domain/slideService.js
  ozkour-back/domain/talks-sheet.js
  ozkour-back/domain/type/slide.ts
  ozkour-back/google-api/sheets.js
  ozkour-back/google-api/slideService.js
  ozkour-back/infrastructure/connect.js
  ozkour-back/infrastructure/googledrive/drive.js
  ozkour-back/infrastructure/googledrive/driveWrapper.js
  ozkour-back/infrastructure/googlesheets/sheetWrapper.js
  ozkour-back/infrastructure/googleslide/googleSlideRepository.js
  ozkour-back/infrastructure/googleslide/slideWrapper.js
  ozkour-back/server.js
  ozkour-back/tests/__snapshots__/sheets.test.js.snap
  ozkour-back/tests/__snapshots__/slide.test.js.snap
  ozkour-back/tests/__snapshots__/slideDataOrganizer.test.js.snap
  ozkour-back/tests/dateUtils.test.js
  ozkour-back/tests/drive.test.js
  ozkour-back/tests/sheets.test.js
  ozkour-back/tests/slide.test.js
  ozkour-back/tests/slideDataOrganizer.test.js
  ozkour-front/.env
  ozkour-front/src/stores/talks.js
Labels: backend, architecture

#113 112-authentification-du-back-en-service-account
  ozkour-back/.gitignore
  ozkour-back/config/auth/credentials.js
  ozkour-back/config/auth/service_account.js
  ozkour-back/config/auth/token.js
  ozkour-back/infrastructure/connect.js
  ozkour-back/infrastructure/googledrive/driveWrapper.js
  ozkour-back/server.js
  ozkour-back/tests/slide.test.js
Labels: enhancement, backend
